/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicewars.states;

import dicewars.Main;
import dicewars.Player;
import gameTools.state.State;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author ganter
 */
public class SettingsState extends State {

    private ArrayList<PlayerEntry> pe_s = new ArrayList();
    
    public void addPlayer(){
        PlayerEntry pe = new PlayerEntry(this);
        pe_s.add(pe);
        panePlayers.add(pe);
        for(PlayerEntry p : pe_s){
            p.setBounds(5, p.getPlayer().getId()*40, Main.GAME_WIDTH-200, 35);
            p.refresh();
        }
        panePlayers.revalidate();
        panePlayers.repaint();
    }
    public void removePlayer(int id){
        for(PlayerEntry p : pe_s){
            if(p.getPlayer().getId() == id){
                panePlayers.remove(p);
                pe_s.remove(p);
                p.getPlayer().dispose();
                break;
            }
        }
        for(PlayerEntry p : pe_s){
            p.setBounds(5, p.getPlayer().getId()*40, Main.GAME_WIDTH-200, 35);
            p.refresh();
        }
        panePlayers.revalidate();
        panePlayers.repaint();

    }
    
    /**
     * Creates new form NewJPanel
     */
    public SettingsState() {
        super("SettingsState", Main.GAME_WIDTH, Main.GAME_HEIGHT);
        initComponents();
        addPlayer();
        addPlayer();
        addPlayer();
        Tps=1;
        maxFps=30;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panePlayers = new javax.swing.JPanel();
        lblMapOptions = new javax.swing.JLabel();
        cBoxTileType = new javax.swing.JComboBox<>();
        lblMapTileType = new javax.swing.JLabel();
        lblMapShape = new javax.swing.JLabel();
        lblMapHoles = new javax.swing.JLabel();
        cBoxMapShape = new javax.swing.JComboBox<>();
        CheckBoxHasHoles = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        btnAddPlayer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPlayerTeam = new javax.swing.JLabel();
        lblPlayerColor = new javax.swing.JLabel();
        lblPlayerType = new javax.swing.JLabel();
        lblPlayerID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panePlayers.setLayout(null);
        jScrollPane1.setViewportView(panePlayers);

        lblMapOptions.setText("Map options:");

        cBoxTileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMapTileType.setText("Tile type:");

        lblMapShape.setText("Map shape:");

        lblMapHoles.setText("Allow holes:");

        cBoxMapShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setText("Done");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddPlayer.setText("Add Player");
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        lblPlayerTeam.setText("Team");

        lblPlayerColor.setText("Color");

        lblPlayerType.setText("Human/AI");

        lblPlayerID.setText("Player #");

        jLabel1.setText("DEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(lblPlayerID)
                .addGap(18, 18, 18)
                .addComponent(lblPlayerType)
                .addGap(52, 52, 52)
                .addComponent(lblPlayerColor)
                .addGap(44, 44, 44)
                .addComponent(lblPlayerTeam)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerType)
                    .addComponent(lblPlayerColor)
                    .addComponent(lblPlayerTeam)
                    .addComponent(jLabel1)
                    .addComponent(lblPlayerID))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMapShape)
                            .addComponent(lblMapTileType)
                            .addComponent(lblMapHoles))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cBoxTileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cBoxMapShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBoxHasHoles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMapOptions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddPlayer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMapOptions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMapTileType)
                            .addComponent(cBoxTileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMapShape)
                            .addComponent(cBoxMapShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMapHoles)
                            .addComponent(CheckBoxHasHoles))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        addPlayer();
    }//GEN-LAST:event_btnAddPlayerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Main.getInstance().setState("MenuState");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxHasHoles;
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cBoxMapShape;
    private javax.swing.JComboBox<String> cBoxTileType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMapHoles;
    private javax.swing.JLabel lblMapOptions;
    private javax.swing.JLabel lblMapShape;
    private javax.swing.JLabel lblMapTileType;
    private javax.swing.JLabel lblPlayerColor;
    private javax.swing.JLabel lblPlayerID;
    private javax.swing.JLabel lblPlayerTeam;
    private javax.swing.JLabel lblPlayerType;
    private javax.swing.JPanel panePlayers;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(State s) {
    }

    @Override
    public void render() {
    }
}
